### PR TITLE
fix bootstrap-table

### PR DESCRIPTION
**Pull request by Lupennat**
removed id from table
reload bootstrap table when message processed

### CODE REVIEW

**Comment by Dibbyo456** [comment]
oh my god. it fucking worked.

**Comment by Dibbyo456** [comment]
@Lupennat I fucking love you man. Please tell me your preferred method, I can do PayPal, Crypto, Gift or anything you want.

**Comment by Dibbyo456** [comment]
@Lupennat Hey man. Waiting for your address.

**Comment by Lupennat** [comment]
@Dibbyo456 can you give me your email?

**Comment by Dibbyo456** [comment]
Sure. me@harry.plus

**Pull request merged**
